# Generated by Django 2.2.4 on 2019-09-09 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samvrombinator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mot',
            old_name='voc',
            new_name='voc_name',
        ),
    ]
