# Generated by Django 2.2.4 on 2019-09-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samvrombinator', '0002_auto_20190909_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabularies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.TextField(blank=True, max_length=50)),
                ('voc_name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Mot',
        ),
    ]
