# Generated by Django 2.2.4 on 2019-09-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samvrombinator', '0003_auto_20190909_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabularies',
            name='words',
            field=models.TextField(),
        ),
    ]
